### ISSUE TITLE
splitting up tests of cassandra and sqlalchemy

### ISSUE THREAD

**Issue by leonh** [johnbywater/eventsourcing#1]
After playing about with Robert Smallshire's kanban example, I was very interested in trying out your more generic event sourcing project.
 
However I know nothing of the Cassandra db. I ran the test suite be noticed tests were failing due to my missing Cassandra dependency. I tried to split out the cassandra tests and sqlachemy tests into different modules. So that my lack of Cassandra was not hampering my ability to test SqlAlchemy.
https://github.com/leonh/eventsourcing/commit/919fad7fca93a1052e25fb39c61046dd971d0b05

**Comment by johnbywater** [comment]
Hey! Thanks a lot for forking.

Good move splitting out the tests :+1:. If Cassandra is running locally with default settings, the tests should pass. But do you think it would be better if the test was skipped when Cassandra isn't running locally?

Will definitely merge your changes. Maybe you wanted to do a pull request into my develop branch when you're ready? I had a look just now through the changes you made - it all looks good to me ;-).

**Comment by leonh** [comment]
Hiya here's a pull request. I don't have any strong opinion about letting tests fail or be skipped. If you were to skip them then you could test if the cassandra package was importable or not. Or more explicitly add a setting/config file where the persistence backend is selected. 

https://github.com/johnbywater/eventsourcing/pull/2

On a side note - one of the things I liked about the sixty-north Kanban example was the file based event store. Obviously that type of store would present problems in production but for learning and generally understanding the technique of event sourcing it was really good to see the basic event appended in a file. (I'm deffo in the learning and kicking-the-tyres stage at this point)

**Comment by johnbywater** [comment]
Thanks for the suggestions. The simplest alternative seems to be skipping the test when the Cassandra package is not importable. I'll try to do that. Good point about the simple file format, the sixty-north Kanban example is neat. SQLite uses a single file, but it would be cool to have a very simple file format.

**Comment by johnbywater** [comment]
Also thanks for the PR! I merged it in the other day ;-).

**Comment by johnbywater** [comment]
Hey Leon, just wanted to let you know I set up a new mailing list for this project. If would be great if you were to join so that we could discuss things a bit better? Here's the link:
https://groups.google.com/forum/#!forum/eventsourcing-users
