### ISSUE TITLE
How to install with Cassandra?

### ISSUE THREAD

**Issue by subokita** [johnbywater/eventsourcing#101]
I'm using pip version 9.01 and I tried using python 3.5, pypy 5.8, and python 2.7
But everytime when I try to install eventsourcing with either cassandra or sqlalchemy, it gives me error like the following:

```
$ pip install eventsourcing[cassandra]
zsh: no matches found: eventsourcing[cassandra]
```

Is there a way that I could install eventsourcing  with the specified event store?

**Comment by subokita** [comment]
Sorry it's my dumb mistake. I'm running zsh, thus I need to escape the brackets

**Comment by johnbywater** [comment]
No worries. Please don't hesitate to open another issue. Good luck, and have fun!
