### ISSUE TITLE
New Slack channel

### ISSUE THREAD

**Issue by johnbywater** [johnbywater/eventsourcing#102]
Hey @renou @julianpistorius @subokita @yarbelkgazia @rogoman @pouledodue @danielccyr @jellevandehaterd @leonh @lukaszb!

In an attempt to improve communications around this project (perhaps we could organise meetings about this project) there's a new Slack channel: https://eventsourcinginpython.slack.com

There's a sign up page which is available for 7 days. Please sign up here:
https://eventsourcinginpython.slack.com/join/shared_invite/MjA2ODA4MTI0OTYyLTE0OTg5ODM1MDMtZjUyNTI1ZWIyZg

Sorry this has taken so long!

**Comment by yarbelkgazia** [comment]
Hey,

Could you resend this to my regular (non-work) github account: yarbelk

James

**Comment by johnbywater** [comment]
Hi @yarbelk, good to hear from you. I think the link above expired by now. But if you send an email to the author email in this file (below), so I get your email address, then I'll send you a Slack invite. Hope all's well. John

https://github.com/johnbywater/eventsourcing/blob/develop/setup.py

**Comment by johnbywater** [comment]
@yarbelk: new invitation link, valid for 7 days or something:

https://join.slack.com/eventsourcinginpython/shared_invite/MjEyMTMzODkxOTkwLTE0OTk4MDQ4MzctMDcyOTg5MjllYw

**Comment by johnbywater** [comment]
@julianpistorius here's a new invitation link, valid for 30 days: https://join.slack.com/t/eventsourcinginpython/shared_invite/MjI0NDEzODA5NzM0LTE1MDIxNzUwMjctNTNmYWMzZTI2Mg

**Comment by johnbywater** [comment]
Here's a new invitation link, valid for 30 days:
https://join.slack.com/t/eventsourcinginpython/shared_invite/enQtMjQyMTA5Njc5MTg1LWM0N2M3OTIzYmNmMGQ4NDk2ZWU3NTI5N2YwMjQ0MDk0MWQ4MGJhYzQ4MjM1ZWNkNGZkMmE5OWU2ZDhhN2ZkMjI

**Comment by johnbywater** [comment]
Here's a new invitation link, valid forever:
https://join.slack.com/t/eventsourcinginpython/shared_invite/enQtMjczNTc2MzcxNDI0LTUwZGQ4MDk0ZDJmZmU0MjM4MjdmOTBlZGI0ZTY4NWIxMGFkZTcwNmUxM2U4NGM3YjY5MTVmZTBiYzljZjI3ZTE
