### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by johnbywater** [johnbywater/eventsourcing#104]
Rewrite the documentation to follow the structure of the library rather than the list of features.

Firstly, document the core event sourcing persistence mechanism ("given infrastructure is setup, when an event is stored, the event can be retrieved"). Use domain event classes from the library to show how to store and retrieve a sequence of events. The aspects of the persistence mechanism are:

- active record classes (stored event schema, indexes and performance of the queries);
- active record strategy (database management system);
- the JSON object encoder and decoder;
- the optional cipher strategy; and
- the event store object which holds it all together.

Secondly, describe how each of the DDD concepts can be implemented using the library classes:

- the layers (interface, application, domain, infrastructure);
- how an aggregate can respond to commands by constructing and applying and publishing events;
- how to replay events to get current state using a mutator function; how an entity factory can work;
- how a repository can provide a dictionary-like interface for accessing domain entities by ID;
- how domain services can work;
- how an aggregate root can work;
- how to use entities within an aggregate;
- how to use value objects within an aggregate;
- how to use an application object both to bind the domain layer and infrastructure layer, and to present application services;
- application policies and publish-subscribe mechanisms;
- how interfaces can use an application object;
- how application logs can allow projections to update themselves from the application state; and
- how notification logs can allow remote projections to update another application.

And then include some example applications.

Anything else?

**Comment by dgonzo** [comment]
I would love to help reimplement the sixty-north Kanban. I feel like it does a good job of explaining aggregates and entities.

**Comment by johnbywater** [comment]
Thanks @dgonzo that's great! You could maybe start by copying this "todo" application we did a couple of weeks ago, and start reworking it into a kanban board? https://github.com/Chris-May/es_todo/blob/master/es_todo/application/base.py

If you start a git repo, I'll help you get it working :-)

There are some tests here, which you could rework to be tests for a kanban board? https://github.com/Chris-May/es_todo/blob/master/es_todo/tests/test_app.py

**Comment by dgonzo** [comment]
@johnbywater do you want me to just fork and work out an example in an examples directory or would you prefer I just create a stand-alone example?

**Comment by johnbywater** [comment]
i guess a new repo would make sense @dgonzo? i think it's possible to fork and detach by asking github support, otherwise you could just copy files?

i guess the "todo list" is like a "board", and "todo item" is like a "card", so the kanban app seems quite similar to the todo app - but moving cards between columns is new, something we can perhaps discuss together?

what else does a kanban app need to do? :-)

**Comment by dgonzo** [comment]
Great. I'll just do a stand-alone example app. It can be linked in README or wiki. 

Kanban has two aggregates Board & WorkItem. 
A Board has one entity: Column

I've read through the ToDo app and vis-a-vis Kanban and you're right there some things worth discussing:

- WIP limit
- Overdue service
- WorkItem projection
- WorkItem Added, Inserted, Removed (ordering)

Lastly, I really love the ASCII "gui" as it's quite illustrative of the processes that make DDD and event-sourcing useful.

**Comment by dgonzo** [comment]
@johnbywater if this thread would be better suited elsewhere happy to accommodate. I'm fond of slack but I've also learned to tolerate email ;-)

**Comment by johnbywater** [comment]
hehe, i don't mind - open a new issue on this project if you want to? or we could discuss it on the slack channel? just let me know, so i can follow you?

**Comment by dgonzo** [comment]
I'll work on an example implementation of Kanban [here](https://github.com/dgonzo/kanban-demo) and update here with progress.

**Comment by dgonzo** [comment]
@johnbywater could you explain the proper use of CollectionsRepository?

**Comment by johnbywater** [comment]
@dgonzo did you mean the library class CollectionRepository? It's an event sourced entity repository, so it needs to be constructed with an event store. It's a repository, so it provides a dictionary-like interface that you can use to retrieve entities by ID. There's a test case which covers it, here: https://github.com/johnbywater/eventsourcing/blob/develop/eventsourcing/tests/test_collection.py#L108

Were you just wondering, or were you having some trouble that I could perhaps help you with?

**Comment by dgonzo** [comment]
That explanation was great. I ran into the class in the todo example and hadn't come across it. Reading through the code base I understood more or less what it did but not why; very helpful.

I'm working on day-job stuff this week and I'll circle back on the eventsourcing-kanban stuff this weekend.

**Comment by dgonzo** [comment]
I had an unrelated question about setters and validation using the `@attribute` decorator. I would have thought the following would capture any "empty" value (e.g., None, "", etc.) but the value is passed through during setting.

```
    @attribute
    def name(self, value):
        if len(value) < 1:
            raise ValueError("Column 'name' must not be empty.")
        else:
            pass
```

I know this boils down to my relative ignorance of decorators (we data scientists are typically poor software engineers) so the above behavior is expected but if validation is desired during setting how might I accomplish that? Should I just use the traditional setter and not use `@attribute`?

**Comment by johnbywater** [comment]
Glad you found the explanation helpful!

Regarding the @attribute decorator, the implementation just doesn't use the body of the decorated method - so the body can be "pass". The decorator completely takes over, and supplies both a getter and a setter. I'm sure there's room for improvement here.

If it were a python @property, the code you wrote above would be a getter, not a setter. But it looks like you're trying to do validation, which is a useful thing to do, but it isn't really supported at the moment. I guess the way setter of @property works could be followed. The following currently isn't supported by the library, but it might be one way to express validation, it might be worth implementing something like this?

```
    @attribute
    def name(self):
        """The name attribute."""

    @name.validate
    def _validate_name(self, value):
        if len(value) < 1:
            raise ValueError("Column 'name' must not be empty.")
```

I'm not sure what to do with the body of the method. I feel bad for throwing it away, but I don't know how to involve it reliably, without having to explain lots of things. The neatest thing seems to be writing a docstring, so that you don't need any other statements.

**Comment by johnbywater** [comment]
@dgonzo If you were interested to learn more about Python decorators, you may wish to look at the way the `@property.setter` is implemented, and try to replicate that to implement @attribute.validate?

**Comment by dgonzo** [comment]
I've got a first end-to-end working on the `user` model. Thank you so much for your patience. I'm coming from the world of stats and data science and your help has been greatly appreciated.

I'd like to add a "Third" category based on my background. These would be truly tertiary to your stated objectives above but I believe the will be compelling.

- how traversing historical events can be used to answer common "BI" questions like user behavior and detailed utilization trends
- how historical events can be used as a rich supply of data for use in forecasting and machine learning
