### ISSUE TITLE
Support Kafka

### ISSUE THREAD

**Issue by johnbywater** [johnbywater/eventsourcing#108]

**Comment by johnbywater** [comment]
Maybe not possible as a full record manager in the library, because can't control concurrency https://issues.apache.org/jira/browse/KAFKA-2260

However, in situations where there is only one thread per sequence, then it would be possible.

**Comment by vladimirnani** [comment]
Right, it might be a mean to transport events rather then store.

https://medium.com/serialized-io/apache-kafka-is-not-for-event-sourcing-81735c3cf5c

**Comment by topiaruss** [comment]
If you need eventsourcing on Kafka, please add weight for [KAFKA-2260](https://issues.apache.org/jira/browse/KAFKA-2260?focusedCommentId=16591460&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16591460).

**Comment by okeyokoro** [comment]
I made a comment suggesting how we could approach [this](https://github.com/johnbywater/eventsourcing/issues/103#issuecomment-477459410)
