### ISSUE TITLE
Aggregate root event subscribe

### ISSUE THREAD

**Issue by vladimirnani** [johnbywater/eventsourcing#133]
Having following aggregate root:

```
class Order(AggregateRoot):
    class SomethingHappened(AggregateRoot.Event):
        pass
```

Subscribing to the event:

```
@subscribe_to(Order.SomethingHappened)
def on_something(e):
    pass
```
Subscriber never gets called.

After debugging `subscribe_to` i see that `event_class`  is `<class 'domain.order.SomethingHappened'>` while `event` var is list so `event_type_predicate` is returning false.

**Comment by johnbywater** [comment]
Good point ;-) thanks for opening the issue.
