### ISSUE TITLE
Actor framework

### ISSUE THREAD

**Issue by johnbywater** [johnbywater/eventsourcing#136]
Serialising aggregate commands would avoid concurrency errors. Application state could be more easily kept in memory, avoiding lots of reads. Thespian seems promising, since it has "convention" mode that runs across a cluster of nodes. Would like to write an application class that uses an actor framework: the repository could return aggregate actors. Could scale by application partition, with each partition having an application actor.

**Comment by vladimirnani** [comment]
I see a lot of benefits in treating each aggregate in a different actor. 

In the following code snippet I have created an actor per aggregate.
```python
from eventsourcing.domain.model.aggregate import AggregateRoot
from eventsourcing.infrastructure.sequenceditem import StoredEvent
from thespian.actors import Actor, ActorSystem, ActorExitRequest


class MakeItSoCommand(object):
    def __init__(self, something):
        self.something = something

    def __str__(self):
        return self.something


class World(AggregateRoot):
    def __init__(self, ruler=None, **kwargs):
        super(World, self).__init__(**kwargs)
        self._history = []
        self._ruler = ruler

    @property
    def history(self):
        return tuple(self._history)

    def make_it_so(self, something):
        self.__trigger_event__(World.SomethingHappened, what=something)

    class SomethingHappened(AggregateRoot.Event):
        def mutate(self, obj):
            obj._history.append(self)


class WorldAggregateActor(Actor):
    world = None

    def receiveMessage(self, message, sender):
        if not self.world:
            self.world = World.__create__()
        if type(message) is StoredEvent and type(message.state) is MakeItSoCommand:
            self.world.make_it_so(message.state.something)
        if message == 'history':
            self.send(sender, self.world.history)
        self.world.__save__()


def get_actor(originator_id, system, actors):
    actor = actors.get(originator_id, None)
    if not actor:
        actor = system.createActor(WorldAggregateActor)
        actors[originator_id] = actor
    return actor


def __main__():
    system = ActorSystem('simpleSystemBase')
    # storing partitioned actors for reuse
    sequences = {}

    # first aggregate
    first_event = StoredEvent(1, 0, "MakeItSo", MakeItSoCommand('dionsaurs'))
    actor = get_actor(first_event.originator_id, system, sequences)
    system.tell(actor, first_event)

    second_event = StoredEvent(1, 1, "MakeItSo", MakeItSoCommand('internet'))
    actor = get_actor(second_event.originator_id, system, sequences)
    system.tell(actor, second_event)

    # second aggregate
    disneyland_event = StoredEvent(2, 0, "MakeItSo", MakeItSoCommand('disneyland'))
    actor = get_actor(disneyland_event.originator_id, system, sequences)
    system.tell(actor, disneyland_event)

    history = system.ask(sequences[1], 'history')
    assert history[-1].what == 'internet'

    history = system.ask(sequences[2], 'history')
    assert history[-1].what == 'disneyland'

    for actor in sequences.values():
        system.tell(actor, ActorExitRequest())

__main__()

```
I wonder how we can address the `sequences` routing. Should it be another actor with list of sequences, kind of a coordinator.

Am I looking the right direction here?

**Comment by johnbywater** [comment]
Wow! that's amazing!

We could probably add this to the library, with the changes you described, without all the process/system complications, as `SimpleActorApplication`.

Not sure what to say about the `sequences` variable. Perhaps it could be renamed `actors`? As I'm sure you see, if the module level functions such as `get_actor()` become methods on a class such as `SimpleActorApplication`, then `actors` could be a member of the object, so then it wouldn't need to be an argument of the function.

Adding recovery in case of failure would make it more or less complete? :-)

**Comment by johnbywater** [comment]
One thought: do you need to send the command with the `StoredEvent` class? Would it work to just send a command object?

**Comment by johnbywater** [comment]
@vladimirnani I did this: http://eventsourcing.readthedocs.io/en/latest/topics/process.html#actor-model

**Comment by vladimirnani** [comment]
Good job, its a pity Im pretty busy these days to continue, though im very interested.

About previous comment: Yes command makes more sense.
