### ISSUE TITLE
exception that might not be expected

### ISSUE THREAD

**Issue by mimoo** [johnbywater/eventsourcing#149]
in https://github.com/johnbywater/eventsourcing/blob/2cfeff4f6bb05078f3f5110e23cba81772061ec8/eventsourcing/utils/cipher/aes.py#L71

this will raise an exception if nonce is empty (`[]`), which is possible since the length of the ciphertext is not checked.

**Comment by johnbywater** [comment]
Hopefully fixed in 7a032d2?

**Comment by mimoo** [comment]
It'd be easier to just do `if len(ciphertext) < 12+16` but yeah that should work :)
