### ISSUE TITLE
EntityWithHashchain.Event.__mutate__ is never called

### ISSUE THREAD

**Issue by chanhosuh** [johnbywater/eventsourcing#164]
I noticed that in the code for `EntityWithHashChain.Created`, the `super` call does not put in the class of `self`, but of its parent:

```
        def __mutate__(self, entity_class=None):
            # Call super method.
            obj = super(EntityWithHashchain.Event, self).__mutate__(entity_class)

            # Set entity head from event hash.
            obj.__head__ = self.__event_hash__

            return obj
```

This means the `__mutate__` of `EntityWithHashChain.Event` is skipped.  In fact, fixing the super call will make the example code in the quickstart guide fail.  Probably the fix should be to remove the method.

**Comment by johnbywater** [comment]
Wow, well spotted! :)) you're good!

**Comment by johnbywater** [comment]
@chanhosuh I fixed it like this: https://github.com/johnbywater/eventsourcing/commit/94ffec3368d8a12b32eafaef6690809622a807b0

**Comment by johnbywater** [comment]
Tests passed so I'll close this. Please reopen if you need to. Many thanks for spotting this issue, and if you spot anything else, please don't hesitate to open another! :)

**Comment by chanhosuh** [comment]
@johnbywater that's great!  I was feeling guilty about posting a sloppy issue and was planning to write a formal PR so I could run your tests etc... but you've pre-empted me :)
