### ISSUE TITLE
Latest release v7.1.4 tests fail

### ISSUE THREAD

**Issue by alexanderlarin** [johnbywater/eventsourcing#175]
I've tried to contribute the project to fix some issues and found that unit tests have fail status
Environment: Windows 10 x64, Python 3.7.0
Run command: python -m unittest
Failed tests:
eventsourcing.tests.core_tests.test_events.TestEventWithTimestamp
AssertionError: Decimal('1563540932.143897') not greater than Decimal('1563540932.143897')
eventsourcing.tests.core_tests.test_events.TestEventWithTimestampAndOriginatorID
AssertionError: Decimal('1563540932.144888') not less than Decimal('1563540932.144888')

And sometimes there blinking assertion in test:
eventsourcing.tests.core_tests.test_utils.TestUtils)
AssertionError: Decimal('1563542114.857965') not greater than Decimal('1563542114.857965')

Is it OK?

**Comment by johnbywater** [comment]
Thank you very much for raising this issue. I tried to fix it in 44f3443dee769e2e30bbccc59bf7ff641b3d31fa. Please reopen if you think there's still something else to be done.
