### ISSUE TITLE
requests library dependency before 2.20 have a security vulnerability

### ISSUE THREAD

**Issue by fearedbliss** [johnbywater/eventsourcing#177]
Hello,

The requests library before 2.20 has a security vulnerability that was fixed in 2.20. We should bump up the library to 2.20 if possible. At the moment it currently has this requirement:

`requests<=2.19.99999`

**Comment by johnbywater** [comment]
Thank you. I just pushed changes for this to  the develop branch: fc7e20ea958c889400da8e615f70c9e0320cfd74. Will release soon!
