### ISSUE TITLE
How to constrain the structure of Aggregrates?

### ISSUE THREAD

**Issue by adnanmuttaleb** [johnbywater/eventsourcing#180]
The default event of DomainEntity, AttributeChanged will allow any attribute to be added to an Entity regardless of its name or its type, so how to impose a structure on a given entity, specifically I want specific attribute names and a specific type for each attribute? should I define custom command and event for each attribute?

**Comment by johnbywater** [comment]
You can use custom commands and events, that's the default thing to do. The basic routine is to have a simple read-only property exposing a private attribute, that is assigned its value in a mutate function from an attribute values of an event triggered by a command method. But it will involve a lot less code to example declare simple event sourced attributes with the `@attribute` decorator.

**Comment by adnanmuttaleb** [comment]
Thank you, I was thinking of something like Fields Type Dict:

```
fields = {
    "name": str,
     "age": int,
     ...
}
```

So we can continue maintaining only one generic AttributeChanged Command.  But I will try custom command, thanks. 

Second question, Is there any examples of how to  declare an Aggregate that use other DomainEntities, I could not find one in the Docs. I think in this case the DomainEntities Commands should be masked unless the invoking object is their Aggregate Entity, right?.

**Comment by johnbywater** [comment]
About the fields dict idea, it seems good to me. You can certainly extend the classes to check the attribute name is in a given list. Just spot the most suitable method to extend. There are probably lots of different ideas. The library, although perfectly adequate for many purposes, is also just a jumping off point for bigger things.

The reason the library says nothing about using domain entities within aggregates is there is nothing to say. You just need to have a Python object that has an ID, and then keep the IDs in a dictionary or something within the aggregate, which will have all the command methods that will manipulate the included domain entities. Hopefully that's a simple thing to do?

Not sure what you mean about "masked" but if you wanted to clarify further, I will try to reply further. :-)

**Comment by adnanmuttaleb** [comment]
Many thanks, I mean according to DDD entities that are not aggregates should not be altered directly, instead they should be altered through their aggregate entities. thank you again.

**Comment by johnbywater** [comment]
Exactly :-) this has come up before, and it was felt there's isn't really anything in particular for the library to do here. It's a just a more complicated data structure, and some custom type of object. And whatever you actually need, which I don't feel I can anticipate very well. But perhaps there could be an example in the documentation that covers this, suggesting one way of doing it, at least. Feel free to start a PR is you fancy having a go? You don't need to prove all the tests are passing before pushing me some changes, I can catch all that ;-)
