### ISSUE TITLE
1.10 release?

### ISSUE THREAD

**Issue by rogoman** [johnbywater/eventsourcing#19]
Any chance you could release the 1.10 version to PyPI? 1.09 doesn't seem to work with MySQL and SQLAlchemy.

`sqlalchemy.exc.CompileError: (in table 'stored_events', column 'event_id'): VARCHAR requires a length on dialect mysql`

This is already fixed in the main branch.

**Comment by johnbywater** [comment]
Yes definitely, thanks for asking about it.

**Comment by johnbywater** [comment]
Just did it: https://pypi.python.org/pypi/eventsourcing/1.0.10

please let me know if there are any problems with it? also i've been focussing on the cassandra end of things recently, so if you know how the sqlalchemy code in this repo could be improved, please let me know or maybe even propose some changes?

**Comment by rogoman** [comment]
Cool, thanks a lot!
