### ISSUE TITLE
How to support  namedtuple  in event state?

### ISSUE THREAD

**Issue by adnanmuttaleb** [johnbywater/eventsourcing#191]
One of my events has a namedtuple in its state. This event mutate the state of its parent entity as follow:

```
    class SomethingAdded(BaseAggregateRoot.Event):
        def mutate(self, obj):
            obj.things = (*obj.things, self.my_namedtuple)   
```

But when restoring the entity from the repository, the `things` attribute has the following structure:

`([...], [...])`

clearly the namedtuple are replaced with list, so how to retrieve the entity while preserve it original state?

**Comment by adnanmuttaleb** [comment]
One of my events has a namedtuple in its state. This event mutate the state of its parent entity as follow:

```
    class SomethingAdded(BaseAggregateRoot.Event):
        def mutate(self, obj):
            obj.things = (*obj.things, self.my_namedtuple)   
```

But when restoring the entity from the repository, the `things` attribute has the following structure:

`([...], [...])`

clearly the namedtuple are replaced with list, so how to retrieve the entity while preserve it original state?

**Comment by johnbywater** [comment]
Thanks for raising the issue.

The library has a JSON encoder which extends the core Python JSON encoder by supporting the following types: UUID, datetime, date, time, Decimal, object instances with __dict__, object instances with __slots__ rather than __dict__, set, and deque. This encoder is used when storing events. There is a matching decoder which supports the same set of types. The decoder is used when retrieving stored events. The general idea is that retrieved events should be equal to the original, but in practice this is only true all the values of an event are supported by the JSON encoder.

So, if you want a retrieved event to be equal to its original state, you need to make sure all of its values are supported by the encoder. Either make sure that you only use types of objects that currently supported by the encoder. Or extend the encoder to support the types you are using that aren't currently supported by the library.

I'm not entirely sure why namedtuple isn't supported, so will look into that. To resolve your issue, since extending the JSON encoder requires some thought, perhaps the easiest thing would be to use something other than a namedtuple in your model? Perhaps a normal object class instance would be ok, or maybe you could use "data class" instead of namedtuple?

**Comment by johnbywater** [comment]
So a "NamedTuple" is a "tuple", and since the Python core JSONEncoder class supports tuples, the library encoder doesn't get asked what to do with tuples, and they are just converted to "JSON arrays" which are they decoded as Python lists. This is similar to when dicts that have integer keys are decoded to have string keys.

So if you use a tuple, it will be converted to a list, and that's a core Python behaviour. So perhaps you could just use a list? Otherwise define an object class, perhaps using __slots__?

I don't know whether it would a good idea to improve the library encoder to support namedtuples, the trouble being that there isn't actually a "namedtuple" supertype, and any "duck typing" might incorrectly identify non-named tuples that happen to have a "_fields" attribute. So although it might be useful, it also seems a bit problematic, but I'm open to suggestions about this.

```
class JSONEncoder(object):
    """Extensible JSON <http://json.org> encoder for Python data structures.

    Supports the following objects and types by default:

    +-------------------+---------------+
    | Python            | JSON          |
    +===================+===============+
    | dict              | object        |
    +-------------------+---------------+
    | list, tuple       | array         |
    +-------------------+---------------+
    | str               | string        |
    +-------------------+---------------+
    | int, float        | number        |
    +-------------------+---------------+
    | True              | true          |
    +-------------------+---------------+
    | False             | false         |
    +-------------------+---------------+
    | None              | null          |
    +-------------------+---------------+
```

**Comment by adnanmuttaleb** [comment]
Thank you for your time. For now I think it is better to go with the object class option. The reason why I a using namedtuple instead of object class, I think value objects is better to be modeled as tuples, while it is better to model entities as class objects .

**Comment by adnanmuttaleb** [comment]
There is a question in SO related to this issue https://stackoverflow.com/questions/43913256/understanding-subclassing-of-jsonencoder. But it seems that overriding the `JSONEncoder` class to support `namedtuple` not an easy task.

**Comment by johnbywater** [comment]
I agree that namedtuple feels like a better fit for value objects. But also feel that maybe object class is good enough. Anyway, I just implemented support for the built-in `tuple` type and for custom `NamedTuple` types in PR #192. It's a feature branch. Not sure what people think about this, whether it's an actual improvement or not (some may prefer the current tuple->list behaviour).

Perhaps a better encoder would reject objects that its matching decoder won't decode to something that equals the original value? We could check for supported types as the first step in the `iterencode` method, but that might slow it down a bit too.

**Comment by adnanmuttaleb** [comment]
I completely agree with you, `decode(encode(obj)) = obj`, because this prevent unexpected behavior that is little hard to detect. or maybe the encoder should allows the encoding process to be carried either in strict mode or not.

**Comment by adnanmuttaleb** [comment]
Although this is irrelevant to the issue  but I do not know elsewhere I can ask the question: is there any features, enhancements you are planning to do, that I may help with?. I have not contributed to any opensource project yet, and I think it is great if I can start in this project.

**Comment by johnbywater** [comment]
Thanks for offering to help, @adnanmuttaleb. Perhaps if you haven't already, you could join the Slack channel and we can chat about it there? If you don't like Slack, we can continue to discuss things here, or elsewhere e.g. by email (mine is in the setup.py file).

**Comment by adnanmuttaleb** [comment]
Slack is OK, but opening the slack invite link, massage says: 

> The invite link is no longer active.

**Comment by johnbywater** [comment]
I'll fix that. The links were said by Slack to be good forever. Just a second...

**Comment by johnbywater** [comment]
This Slack invitation link should work @adnanmuttaleb: https://join.slack.com/t/eventsourcinginpython/shared_invite/enQtMjczNTc2MzcxNDI0LTJjMmJjYTc3ODQ3M2YwOTMwMDJlODJkMjk3ZmE1MGYyZDM4MjIxODZmYmVkZmJkODRhZDg5N2MwZjk1YzU3NmY

**Comment by mpickering** [comment]
I am not sure this properly fixed. If I try to use a dictionary keyed by tuples in the event state then the tuple is decoded to a list still with version 0.8.

```
{} ['BOK', 10]
Traceback (most recent call last):
  File "example.py", line 71, in <module>
    world = app.repository[fixed_id]
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 72, in __getitem__
    entity = self.get_entity(entity_id)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 106, in get_entity
    entity_id, gt=gt, lte=at, initial_state=initial_state
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 161, in get_and_project_events
    return self.project_events(initial_state, domain_events)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/infrastructure/eventplayer.py", line 47, in project_events
    return reduce(self._mutator_func, domain_events, initial_state)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/infrastructure/eventplayer.py", line 64, in mutate
    return event.__mutate__(initial)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 332, in __mutate__
    obj = super(EntityWithHashchain.Event, self).__mutate__(obj)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 190, in __mutate__
    return super().__mutate__(obj)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 533, in __mutate__
    obj = super(TimestampedEntity.Event, self).__mutate__(obj)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/domain/model/entity.py", line 453, in __mutate__
    obj = super(VersionedEntity.Event, self).__mutate__(obj)
  File "/nix/store/gp48rh3dsc32d27nm7wkqc9b4wbdwlz1-python3-3.7.4-env/lib/python3.7/site-packages/eventsourcing/domain/model/events.py", line 59, in __mutate__
    self.mutate(obj)
  File "example.py", line 37, in mutate
    aggregate.maps[self.key] = self.meta
TypeError: unhashable type: 'list'
```

**Comment by johnbywater** [comment]
Thanks for the feedback @mpickering. Please could you show the code in example.py? I don't know how to replicate this. When I attempt to encode `{(1,2): 3, (4,5): 6}` I get `TypeError: keys must be str, int, float, bool or None, not tuple` from `python3.7/json/encoder.py", line 257, in iterencode`.

**Comment by mpickering** [comment]
Here is a minimal example. If you run this script twice you will see the state gets decoded incorrectly. It would be better to error in this case imo rather than leave a latent bug which might show up very rarely. 

https://gist.github.com/847eb9e0f4897f24d6fab5cce74364e1

```
> python --version
Python 3.7.4
> python -c "import eventsourcing; print(eventsourcing.__version__)"
8.0.0
> rm test
> python minimal.py 
<eventsourcing.infrastructure.eventsourcedrepository.EventSourcedRepository object at 0x7f2c48a36990>
b81d160d-d7ef-45ab-a629-c7278082a845
0 Info(club='A')
{} 0
{0: Info(club='A')}
> python minimal.py 
<eventsourcing.infrastructure.eventsourcedrepository.EventSourcedRepository object at 0x7fea1b6ee910>
{} 0
<__main__.World object at 0x7fea1b6ee950>
b81d160d-d7ef-45ab-a629-c7278082a845
{0: ['A']}
```

**Comment by johnbywater** [comment]
Thanks for the info @mpickering. I can see the containers are getting the treatment I thought they would... I'll see what I can do about this!

**Comment by johnbywater** [comment]
Does this help? 6c79fa1259f8b0cba74ca5088275fa71036a3ef5
