### ISSUE TITLE
Production applications?

### ISSUE THREAD

**Issue by slangwald** [johnbywater/eventsourcing#216]
Hi,

I am dabbling around with this project now for a while and I see the theoretical benefits, however, thinking of using it in an actual client project looks like a risky move, as I haven't seen any references to already existing "real world" applications.  Or Developers who did projects with it to chat to. So to the creator @johnbywater is this project running in the wild?

Thanks :)

**Comment by johnbywater** [comment]
Thanks for your interest @slangwald. Yes the library has been used by commercial companies in production for several years. They don't publicise their commercial usage of it, and I don't brag about it. But I have helped companies in London and around the world, and there are others that I haven't been involved with that have told me about their usage. If you would like support, please join the Slack workspace. I also provide professional support if you need help with your project. It should be quite obvious how to get going building a model and so on. But when it comes to operational questions, and more sophisticated modelling, you need to understand what's happening quite well, and that's where people tend to ask for guidance and support. There's also a distilled version of the library that will be available soon, which is another option to consider.
