### ISSUE TITLE
Running a system of more than two applications

### ISSUE THREAD

**Issue by ehuebner** [johnbywater/eventsourcing#227]
Hi,
my team and me just did an event storming for a new project and we will use the eventsourcing library. After some first steps I struggle a bit with running more than two applications in a system. The World-Counter-Example works like a charm but we will have 4 applications and the number will increase

AppA, AppB, AppC & AppD. The Communication between that applications is the following:
AppA --> AppC (policy in AppC processes event of AppA)
AppB --> AppC (policy in AppC processes event of AppB)
AppC --> AppD (policy in AppD processes event of AppC)
AppA --> AppD (policy in AppD processes event of AppA)

`system = System(pipes=[[AppA, AppB, AppC, AppD]])`

Obviously this will not work because the library creates edges out of the given nodes. But how can I run the system we designed?

**Comment by ehuebner** [comment]
I have already tried it and it did not work.
My Event of AppB uses Transcodings for some custom event attributes. Recording the events & snapshotting works fine, but the policy not. Now I tried producing an event with setting the custom event attributes of B to `None` the policy of AppC is now triggered. But this works only without using Transcodings.

Do you have any idea that explains that behaviour?

**Comment by ehuebner** [comment]
I only implemented the transcoder in AppB and not in AppC. But now that you say it, it makes total sense to me to have the transcoder & transcoding implemented on both sides.

There was no exception thrown, that is why I also thought the way you suggested in your answer is the wrong way. It is just silently not working when the application that implements the policy does not know the transcodings.

**Comment by johnbywater** [comment]
@ehuebner I'm glad you got it working! Well done.

I'm very interested to understand how this error was silent. I've been investigating, and can see exceptions being raised in test output, when I arrange things to be broken in this way. Please can you replicate what you are doing so I can understand your experience?
