### ISSUE TITLE
Question: how to make domain event listener without making another aggregate

### ISSUE THREAD

**Issue by ahnsv** [johnbywater/eventsourcing#231]
Hi folks,

I am recently into DDD and event-driven architecture, and just bumped into this amazing project. 
I refactored my own project using this library (which is awesome), but I wonder if I can make domain event listener without making another aggregate. 

Let me be more specific. Say, my application create an "Order" (which is an aggregate), and I want to make a slack notification on an "OrderCreated" domain event. The [guide](https://eventsourcing.readthedocs.io/en/v9.1.1/topics/system.html#system-of-applications) tells that I should make another aggregate(i.e., Counter as an Aggregate, Counters as a ProcessApplication). I am looking for a simpler interface for listening to domain event, so that I can make handler functions outside of my business logic. 

Below are my imaginary code,
```python
@dataclass
class Order(Aggregate):
  product_id: str
  username: str

@listen('Created')
def handle_order_created(event):
  slack.send_info(event) 

@listen('OrderFailed')
def handle_order_failed(event):
  slack.send_error(event)
```

Any idea on this kind of implementation? I assume this can be done with notification readers but I failed to integrate that with my server in a seamless way. 

Many thanks

**Comment by ahnsv** [comment]
https://github.com/ahnsv/muskat-event
Here is my repo that implements a simple Order service using eventsourcing
(Please mind my Korean commits and comments)

**Comment by johnbywater** [comment]
Thanks for asking the question,and for making your code available! You can try to implement the notify method of the application that will save these aggregates, to post the event info to an API after they are saved. Or if you want to do it when events are triggered, then you could extend the aggregate's trigger method? If you want to refactor that implementation into a decorator, I'm sure you would be able to figure that out with a little bit of thought. Let me know if this works for you, I would be very interested to see the results. If you get stuck, or need any more help with this or anything else, don't hesitate to ask again :)
