### ISSUE TITLE
slack channel for the project?

### ISSUE THREAD

**Issue by renou** [johnbywater/eventsourcing#26]
Hi John!

Do you want to start a slack channel for this project? For project discussion. :)

Bo

**Comment by johnbywater** [comment]
We could :) i don't know how to enable open registrations though.

**Comment by johnbywater** [comment]
https://eventsourcing.slack.com/ but you need an email address in my domain? I'm sorry I don't know what else to do. If you wanted to suggest how it should be configured, just say :)

**Comment by renou** [comment]
yeah, seems it's a private org.
