### ISSUE TITLE
Question: adding a new application to an existing system

### ISSUE THREAD

**Issue by d-m** [johnbywater/eventsourcing#281]
Is it possible with this library to add a new application to an existing system and have it process existing domain events of its upstream applications?

**Comment by peterDijk** [comment]
yes you can `pull_and_process(leader_name=UpstreamApplication.__name__, start=1)` to process events from the start.

**Comment by johnbywater** [comment]
Alternatively @d-m, you can add a new application to a system definition and restart your system runner. Which does what @peterDijk said.
