### ISSUE TITLE
Can't start the SingleThreadedRunner again after closing it

### ISSUE THREAD

**Issue by TorecLuik** [johnbywater/eventsourcing#282]
Hey,

I was trying out stopping and starting my (SingleThreadedRunner) runner but it fails.

The little test below raises this RunnerAlreadyStarted exception at the final `runner.start()` call (so after closing).
I think the `close()` of SingleThreadedRunner probably should reset that `is_started` variable? 
Or is it not intended to work? at least the error is wrong then.

```
def test_runner():
    # Create a System instance with the necessary components
    system = System(pipes=[[WorkflowTracker, JobAccounting]])
    runner = SingleThreadedRunner(system)
    runner.start()

    # Get the application
    wft = runner.get(WorkflowTracker)

    # when
    assert wft.closing.is_set() is False
    runner.stop()
    assert wft.closing.is_set() is True
    
    runner.start()
    wft2 = runner.get(WorkflowTracker)
    assert wft2.closing.is_set() is False
    
```

```
        if self.is_started:
>           raise RunnerAlreadyStarted()
E           eventsourcing.system.RunnerAlreadyStarted
```

**Comment by johnbywater** [comment]
Hi @TorecLuik,

Thanks for raising this issue. Sorry it's taken me a little while to reply. I was away cycling for a couple of months.

It might be nice if one could restart a runner after stopping it. However, that's not implemented. Instead, you should reconstruct the runner and start a fresh instance.

I know this probably seems a bit odd in the case of the SimpleThreadedRunner. But the idea was to avoid the potential complications of restarting more complicated runners, and to have a consistent behaviour across all of them.

So please just reconstruct a runner if you want to stop and start again :-)

Hope that's alright?

Best wishes,

John
