### ISSUE TITLE
EventStore

### ISSUE THREAD

**Issue by pouledodue** [johnbywater/eventsourcing#4]
Is there an example somewhere how to use it with EventStore (geteventstore.com) (hydrate aggregate from events stored in EventStore)

**Comment by johnbywater** [comment]
Thanks for your question. I haven't looked into how to read/write events from/to EventStore.

**Comment by johnbywater** [comment]
Somebody at work also asked me about this today. Do you know much about it / how we could do it?

**Comment by johnbywater** [comment]
Could probably make a stored event repository using this Python client for EventStore: https://github.com/Phontan/EventStore.PythonClientAPI

Would anybody actually find this useful really, or would it be more of a curiosity? I'm wondering what you can do with EventStore that you can't do with e.g. Cassandra?

I'm guessing it's in a position to do optimistic concurrency control better than a read and a write against Cassandra, that could be checked I suppose. It could even serialise access to a stream, but I don't see how that could always work e.g. in a distributed situation and scale linearly. I'm becoming curious to see what qualities it has.

It's got pub-sub, and so has e.g. Redis, but I guess if an originating application only needs to publish an event to the event store, and receiving applications can subscribe to it, that helps keep infrastructure simple. However, if the application changed to use something else for persistence of events, then at the same time an alternative pub-sub system would be needed, and the receiving application would need to subscribe to that instead. I guess that's not a problem.

I don't know if it always enforces an integer sequence on every stream, if so perhaps it couldn't be used for e.g. a log entity that doesn't maintain a version number, unless the expected version parameter was derived by causing an exception to be raised which would be absurd. I'm sure that's not a big problem.

On reflection, it seems to have useful and perhaps unique qualities, in particular the optimistic concurrency control of the event streams might be very useful if it is really solid, and might actually be needed by some people.
