### ISSUE TITLE
More in depth documentation

### ISSUE THREAD

**Issue by yarbelk** [johnbywater/eventsourcing#52]
The documentation now does a good job at explaining how to build your own custom parts into a toy application, but it doesn't document how to use all of the parts you have created, such as `EventSourcedApplication`, and the various built in Event types.

It would be nice to get the documentation into readthedocs, with more in depth docs on usage

**Comment by johnbywater** [comment]
Thank you. Totally agree. The README file has way too much for one file. The design seems to have stabilised, lots of things are undocumented, it's time to write more structured documentation. Hopefully I will find time before too long! If you're interested, please feel free to suggest a structure, or describe more what it should contain or enable?

**Comment by yarbelkgazia** [comment]
started this - I will do some basic structuring and a pull request tonight after work; going to focus on trying to get a basic app with aggregates up and running before doing that.

**Comment by johnbywater** [comment]
FYI, just fixed up the README test to cover the code snippets in the new .rst dos, changes in PR #61. I'm expecting the PR to go red because the snippets need updating, I'll fix them up tomorrow.

**Comment by yarbelk** [comment]
**NICE**, I've not seen this before.  It is awesome.

**Comment by johnbywater** [comment]
Thanks! I've been working on it today, have split the tutorial into a "user guide" with eight separate files, five are passing, just got three files left. Have started to make more use of library classes, since otherwise each file would have to define a lot of stuff, since each is tested independently. That's probably a good thing. ?

**Comment by johnbywater** [comment]
http://eventsourcing.readthedocs.io/en/latest/

**Comment by johnbywater** [comment]
Since this is a general request, and the documentation is now a bit more in depth than it was, I'll close this issue in favour of more particular points of improvement. Feel free to reopen if you don't think that's appropriate!
