### ISSUE TITLE
Cassandra Datastore

### ISSUE THREAD

**Issue by yarbelk** [johnbywater/eventsourcing#56]
using v2.1.1
When setting up a casandra `EventSourcedApplication`, how is the `CassandraDatastore` used?

In the readme for SQLAlchemy, it (and in the code) is an argument to `SQLAlchemyActiveRecordStrategy`, but this is not part of `CassandraActiveRecordStrategy`.  As such, I cannot figure out how to setup and use a datastore for cassandra

**Comment by johnbywater** [comment]
You got it. It's very similar to SQLAlchemy, just don't give the Cassandra datastore object to the Cassandra active record strategy object. Create the Cassandra datastore object and call setup_connection() and setup_tables(). Then instantiate and use the Cassandra active record strategies with referring to the datastore object. I just added a section to the README file about it (currently in PR #57, will merge when green) showing how to use Cassandra.

https://github.com/johnbywater/eventsourcing/pull/57/files#diff-04c6e90faac2675aa89e2176d2eec7d8R889

The code snippets are tested so it should work. Let me know if it works for you?

**Comment by yarbelkgazia** [comment]
LGTM.

**Comment by johnbywater** [comment]
Just to link things up, there is now a page in the documentation about using Cassandra here:

http://eventsourcing.readthedocs.io/en/latest/topics/user_guide/cassandra.html
