### ISSUE TITLE
Read events from DynamoDB

### ISSUE THREAD

**Issue by pouledodue** [johnbywater/eventsourcing#7]
With the rise of ES/CQRS with DynamoDB Streams-->AWS Lambda, do you plan to add support for reading events from DynamoDB? ^_^

**Comment by johnbywater** [comment]
Good idea! Yes https://github.com/johnbywater/eventsourcing/commit/cbcb765919e18d4f17ed92817583f4432962b07f :-)

**Comment by pouledodue** [comment]
:-)
