### ISSUE TITLE
MySQL requires length of String column defined

### ISSUE THREAD

**Issue by renou** [johnbywater/eventsourcing#9]
Hi! When I'm use eventsouring against MySQL, it gives an error on migrating the database:

> sqlalchemy.exc.CompileError: (in table 'stored_events', column 'event_id'): VARCHAR requires a length on dialect mysql

Should we add length to the library or do we need to handle schema creation manually?

Thanks!

**Comment by johnbywater** [comment]
Yes add a length if it makes it work :-).

**Comment by renou** [comment]
Thanks! Would you like me to create a PR?

**Comment by johnbywater** [comment]
Yes, thanks a lot, that would be great.

**Comment by johnbywater** [comment]
#10
